#!/usr/bin/env python3
"""Sanitize AGENTS-LOCAL-USER.md and emit a handoff prompt for a meshly agent.

WHY A SANITIZER AT ALL, GIVEN THE DESTINATION IS TRUSTED
--------------------------------------------------------
The receiving agent works in a private repo, so meshly's own repository names,
org names and technical findings are fine to send — stripping those would make
the handoff useless, which is the failure mode a blunt redactor would have.

What must not travel is the OPERATOR'S PERSONAL CONTEXT: a personal domain, a
residential IP address and its reverse-DNS name, a home network's nameservers.
Those are in the local file legitimately — an agent working here needed them —
and they have no business in a prompt handed to another runtime, pasted into
another session's transcript, and persisted in its history. The bar rises with
reach, and a prompt to another agent travels further than a local file.

Secrets are a separate matter and are refused outright rather than redacted:
if one is present, emitting *anything* derived from the file is the wrong move,
because a sanitizer that quietly drops a token teaches you to trust it with
tokens.

FAIL CLOSED, AND VERIFY THE OUTPUT NOT THE INPUT
------------------------------------------------
The redaction is applied, and then the RESULT is re-scanned for every pattern.
If any survives, this exits non-zero and prints nothing usable. That ordering
matters: checking the input tells you what you meant to remove, checking the
output tells you what you actually removed, and only the second is evidence.
An overlapping or malformed pattern that silently fails to substitute is
exactly the case a pre-check misses.

Exit codes follow the house contract:
  0  a sanitized prompt was written
  1  redaction left a pattern behind, or a secret was found — nothing emitted
  2  cannot analyze: the source file is missing, empty, or unreadable
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

EXIT_OK = 0
EXIT_REFUSED = 1
EXIT_CANNOT_ANALYZE = 2

SOURCE = "AGENTS-LOCAL-USER.md"

# (pattern, replacement, why). Each pattern is re-applied to the OUTPUT as a
# residue check, so a replacement must not itself match the pattern.
REDACTIONS: list[tuple[str, str, str]] = [
    # ORDER MATTERS, and getting it wrong is silent. The nameserver rule must
    # run BEFORE the bare-domain rule: the other way round, the domain is
    # already a placeholder by the time this runs, so the pattern matches
    # nothing and leaves `a.ns.<operator-personal-domain>` in the output. The
    # residue check does not catch that, because no real literal remains —
    # it is merely wrong, not leaky. A more specific pattern always precedes
    # the general one it contains.
    (
        r"\b[a-z]\.ns\.diablogato\.com\b",
        "<operator-personal-nameserver>",
        "self-hosted nameservers on the operator's home network",
    ),
    (
        r"\bdiablogato\.com\b",
        "<operator-personal-domain>",
        "a personal domain of the operator's, not a meshly asset",
    ),
    (
        r"\b66\.124\.153\.90\b",
        "<operator-residential-ip>",
        "a residential IP address, which locates a person",
    ),
    (
        r"\badsl-[\d-]+\.dsl\.[a-z0-9]+\.pacbell\.net\b",
        "<operator-residential-ptr>",
        "reverse DNS naming the operator's ISP and exchange",
    ),
    (
        r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b(?!/)",
        "<ip-redacted>",
        "any bare IPv4 literal; documentation ranges are not worth an exception here",
    ),
]

# Patterns that are refused outright. Shapes, not values.
SECRET_SHAPES: list[tuple[str, str]] = [
    (r"gh[pousr]_[A-Za-z0-9]{16,}", "a GitHub token"),
    (r"github_pat_[A-Za-z0-9_]{20,}", "a GitHub fine-grained PAT"),
    (r"-----BEGIN [A-Z ]*PRIVATE KEY-----", "a private key"),
    (r"\bAIza[0-9A-Za-z_\-]{30,}\b", "a Google API key"),
    (r"\bya29\.[0-9A-Za-z_\-]+", "a Google OAuth access token"),
    (r'"private_key"\s*:', "a service-account JSON key"),
    (r"(?i)\b(?:password|passwd|secret|api[_-]?key|client[_-]?secret)\s*[:=]\s*\S{8,}", "a credential assignment"),
]

PREAMBLE = """\
# Handoff: meshly-side work from the google-cloud-github-runner fork

You are a **meshly** agent. This prompt was generated by `just export-handoff`
in the public fork at `Meshly-Open-Source/google-cloud-github-runner`, by a
session that is **not permitted to write to any meshly repository** — which is
why this is a prompt and not a commit.

## How to treat this

* **It is a proposal, not an instruction.** It was written by an agent that
  could not run your repo's gates. Evaluate each item against the code before
  acting; where this text and the code disagree, the code wins.
* **Apply your own gates.** Your repo's hooks, approval rules and CI exist
  because this handoff bypassed none of them — it bypassed the authoring side.
* **Verify before you claim.** Anything below described as verified was
  verified in the FORK, not in your tree. Re-establish it where it matters.
* Personal details of the operator have been redacted and appear as
  `<...>` placeholders. If you need one, ask jw in conversation rather than
  reconstructing it.

---

"""

TRAILER = """

---

## Suggested first actions

1. Read the "Open" section above and reconcile each item against `origin/main`
   before trusting it — some of it is hours old and the queue moves.
2. For anything touching a contract, follow the Ship Plan discipline in your
   repo's own guide; this handoff does not substitute for it.
3. If an item turns out to be already done, say so and drop it rather than
   re-deriving it. A stale premise is the defect, not the work.
"""


def refuse(message: str) -> int:
    print(f"export-handoff: REFUSED — {message}", file=sys.stderr)
    print("  Nothing was written. Fix the source file and re-run.", file=sys.stderr)
    return EXIT_REFUSED


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=SOURCE)
    parser.add_argument("--out", default="-", help="output path, or - for stdout")
    args = parser.parse_args()

    src = Path(args.source)
    try:
        raw = src.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(
            f"export-handoff: CANNOT ANALYZE — {src} does not exist.\n"
            f"  It is intentionally untracked (see .git/info/exclude), so it is "
            f"local to one clone and may simply not have been written here.",
            file=sys.stderr,
        )
        return EXIT_CANNOT_ANALYZE
    except OSError as exc:
        print(f"export-handoff: CANNOT ANALYZE — cannot read {src}: {exc}", file=sys.stderr)
        return EXIT_CANNOT_ANALYZE

    if not raw.strip():
        # An empty source would sanitize perfectly and produce a prompt with no
        # content — a clean result that transmits nothing.
        print(
            f"export-handoff: CANNOT ANALYZE — {src} is empty. An empty file "
            "sanitizes trivially and would emit a prompt with nothing in it.",
            file=sys.stderr,
        )
        return EXIT_CANNOT_ANALYZE

    for pattern, what in SECRET_SHAPES:
        if re.search(pattern, raw):
            return refuse(
                f"the source appears to contain {what}. Refusing to emit anything derived "
                "from it rather than redacting: a sanitizer that quietly drops credentials "
                "teaches you to trust it with credentials. Remove it from the source."
            )

    body = raw
    applied: list[str] = []
    audit: list[str] = []  # stderr only; may contain the literals
    for pattern, replacement, why in REDACTIONS:
        body, n = re.subn(pattern, replacement, body)
        if n:
            # The `why`, never the pattern. A pattern that matches a personal
            # domain CONTAINS that domain, so printing patterns in the output
            # re-leaked every literal this function had just removed.
            applied.append(f"{n}x — {why}")
            audit.append(f"{n}x {pattern}  ({why})")

    note = "\n".join(f"* {a}" for a in applied) or "* nothing matched"
    out = (
        PREAMBLE
        + body.rstrip()
        + TRAILER
        + "\n\n---\n\n## Redactions applied before this prompt left the fork\n\n"
        + note
        + "\n"
    )

    # Residue check on the ENTIRE ASSEMBLED OUTPUT, not on the body.
    #
    # This checks `out` and not `body` because of a real bug caught here: the
    # footer listed the regex PATTERNS, and a pattern that matches a personal
    # domain necessarily contains that domain. The body was clean, the check
    # passed, and the emitted file leaked every literal in its own audit
    # trail. Verify what SHIPS, not an intermediate value.
    residue = [why for pattern, _replacement, why in REDACTIONS if re.search(pattern, out)]
    if residue:
        return refuse(
            "redaction left a pattern in the EMITTED OUTPUT:\n    "
            + "\n    ".join(residue)
            + "\n  A substitution did not take, a replacement matches its own pattern, or "
            "something added after redaction reintroduced a literal."
        )

    if args.out == "-":
        sys.stdout.write(out)
    else:
        Path(args.out).write_text(out, encoding="utf-8")
        print(f"export-handoff: wrote {args.out} ({len(out)} bytes)", file=sys.stderr)
    for a in audit:
        print(f"export-handoff: redacted {a}", file=sys.stderr)
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
